server:
  port: 1010

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1010/eureka/

#security:
#  basic:
#    enabled: false